### ISSUE TITLE
The SEP-8 approval server should identify "Rejected" transactions

### ISSUE THREAD

**Issue by marcelosalloum** [stellar/stellar-demo-wallet#119]
### Sumary

The [SEP-8] approval server should identify "Rejected" transactions. 

### Request

According with SEP-8 the [request format](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#post-endpoint) expected by the approval server should look like:
#### `POST /tx_approve`

**Request:**
```javascript
{
  "tx": "AAAAAHAHhQtYBh5F2zA6..." // the transaction XDR
}
```

**Response:**
```javascript
{
  "status": "rejected",
  "error": "The destination account is blocked." // the error message
}
```

### Criteria

I could think of the following criteria to reject a transaction (there could be more):
* if no transaction is submitted, respond with `{"status":"rejected", "error":"Missing parameter \"tx\""}`
* if can't parse XDR respond with `{"status":"rejected", "error":"Invalid parameter \"tx\""}`
* is the transaction `sourceAccount` the same as the server distribution account? If so, reject with `{"status":"rejected", "error":"The source account is invalid."}`
* are there any operations where the `sourceAccount` is the server distribution account? If that operation is not of the type `AllowTrust` then respond with `{"status":"rejected", "error":"There is one or more unauthorized operations in the provided transaction"}`
* If all of that pass we can respond with `{"status":"rejected", "error":"Not implemented."}` for now.

### Toml File

We should remember to update the toml file with the [SEP-8 fields], something in the format:
```toml
[[CURRENCIES]]
code="GOAT"
issuer="GD5T6IPRNCKFOHQWT264YPKOZAWUMMZOLZBJ6BNQMUGPWGRLBK3U7ZNP"
regulated=true
approval_server="https://goat.io/tx_approve"
approval_criteria="The goat approval server will ensure that transactions are compliant with NFO regulation"
```

Our server is deployed in https://regulated-assets-approval-server.dev.stellar.org/health

[SEP-8]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md
[SEP-8 fields]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md#example
